#!/usr/bin/env bash

if [ -f "$BUNVM_ETC/current" ]; then
    VERSION="$(cat "$BUNVM_ETC/current")"
    if [ -n "$VERSION" ]; then
        bunvm_msg_success "Current version: $VERSION"
    else
        bunvm_msg_info "No active version."
    fi
else
    bunvm_msg_info "No active version."
fi
